language: php

php:
- 7.1.3
- 7.2

services:
  - docker

before_install:
- docker pull kennethreitz/httpbin
- docker run -d -p 8888:80 kennethreitz/httpbin

install: travis_retry composer install --no-interaction --prefer-source

script:
  - php -r 'var_dump(php_sapi_name());'
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover clover.xml
  - composer phpcs
  - composer phpstan

after_success:
  - composer require --dev php-coveralls/php-coveralls
  - vendor/bin/php-coveralls -v -x clover.xml -o coveralls-upload.json
